---
# tasks file for gaia
- name: installing packages
  package:
        name:
            - gcc
        state: latest

- name: Install gaia
  copy:
      src: "{{ item }}"
      dest: /usr/local/bin/
      mode: 755
  with_items:
     - gaiad
     - gaiacli
  become: true
- name: Init genesis
  command:  "gaiad init {{ moniker }} --chain-id  {{ chainID }} -o"
  register: genesis
- debug: 
     var: genesis.stderr
- name: modifing configuration file config.toml
  template:
     src: config.toml.j2
     dest: /home/bobby/.gaia/config/config.toml
  when:  inventory_hostname in groups['validator'] 
- name: modifing configuration file config.toml for sentry node
  template:
       src: config2.toml.j2
       dest: /home/bobby/.gaia/config/config.toml
  when:  inventory_hostname in groups['sentry'] and validator_node_id is defined 
- name:  "adding {{ moniker }} key in backend ring"
  command: "gaiad keys add {{ moniker }} --keyring-backend test"
  register: key

#- debug:
#      msg: "{{ key.stdout_lines[2].split(': ').1 }}"
- name: adding genesis-account
  command: "gaiad add-genesis-account  {{ key.stdout_lines[2].split(': ').1 }} 10000000000stake,1000000000000uatom "
- name: creating gentx
  command: "gaiad gentx {{ moniker }} 10000000000stake --chain-id {{ chainID }}  --keyring-backend test"
  register: gentx
  ignore_errors: true

- name: getting transaction details
  command: "cat {{ gentx.stderr.split('to').1 }}"
  register: transaction
- debug: 
     var: transaction.stdout
  ignore_errors: true
- name: collect gentxs
  command: "gaiad collect-gentxs"
  register: collect
#- command: "rm -rf .gaia"
